
#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/newcovid_complex.out
#$ -e $HOME/newcovid_complex.err
#$ -t 1-1
#$ -l tmem=15G
#$ -l h_rt=18:00:00
#$ -l gpu=true
conda activate libkge_new
export LANG="en_US.utf8"
export LANGUAGE="en_US:en"
cd $HOME/Dissertation/Aladdin/biolink/



test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py --data covid --mcl True --batch-size 50 --epochs 100 --embedding-size 200 --learning-rate 0.1 --regulariser n3 --reg-weight 0.001 --optimizer adagrad --quiet 
