#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/trivec_auc.out
#$ -e $HOME/trivec_auc.err
#$ -t 1-2
#$ -l tmem=15G
#$ -l h_rt=10:00:00
#$ -l gpu=true

export LANG="en_US.utf8"
export LANGUAGE="en_US:en"

conda activate libkge_new

cd ${HOME}/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py  --data pse --model trivec --epochs 100 --batch-size 5000 --embedding-size 100 --learning-rate 0.01 --regulariser n3 --reg-weight 0.01 --nb-negs 6 --valid --auc --quiet
