#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/tucker.out
#$ -e $HOME/tucker.err
#$ -t 1-2
#$ -l tmem=15G
#$ -l h_rt=10:00:00
#$ -l gpu=true

export LANG="en_US.utf8"
export LANGUAGE="en_US:en"

conda activate libkge_new

cd ${HOME}/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py  --data fb15k2 --model tucker --mcl True --epochs 500 --batch-size 128 --embedding-size 200 --rel-emb-size 200 --optimizer adam --learning-rate 0.0005 --regulariser n3 --reg-weight 0 --lr_decay 1.0 --quiet
