#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/tucker_covid_test_bayes.out
#$ -e $HOME/tucker_covid_test_bayes.err
#$ -t 1-1
#$ -l tmem=15G
#$ -l h_rt=10:00:00
#$ -l gpu=true

export LANG="en_US.utf8"
export LANGUAGE="en_US:en"

conda activate libkge_new

cd ${HOME}/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py  --data covid --model tucker --mcl True --epochs 100 --batch-size 128 --embedding-size 79 --rel-emb-size 84 --learning-rate 0.009 --regulariser n3 --reg-weight 0.05 --quiet
