#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/auc_best_pse_cplex_NEW.out
#$ -e $HOME/auc_best_pse_cplex_NEW.err
#$ -t 1-1
#$ -l tmem=15G
#$ -l h_rt=18:00:00
#$ -l gpu=true
conda activate libkge_new
export LANG="en_US.utf8"
export LANGUAGE="en_US:en"
cd $HOME/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py --data pse --mcl True --batch-size 1024 --epochs 100 --embedding-size 200 --learning-rate 0.593 --regulariser n3 --reg-weight 1.432e-06 --optimizer adagrad --quiet --load --auc --save_model_name ccplex_batch1024_es_200_reg_n3_rw_1432_pse
