#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/save_pse_tucker_BCE.out
#$ -e $HOME/save_pse_tucker_BCE.err
#$ -t 1-1
#$ -l tmem=15G
#$ -l h_rt=18:00:00
#$ -l gpu=true
conda activate libkge_new
export LANG="en_US.utf8"
export LANGUAGE="en_US:en"
cd $HOME/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py --data pse --mcl True --loss bce --model tucker --batch-size 1024 --epochs 100 --embedding-size 200 --rel-emb-size 200 --learning-rate 0.024 --regulariser n3 --reg-weight 1.230e-10 --optimizer adagrad --quiet --auc --save_model_name TuckEr_BCE_batch1024_es_200_rs_200_reg_n3_rw_123_lr_024_pse
