#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/array.out
#$ -e $HOME/array.err
#$ -t 1-10
#$ -l tmem=15G
#$ -l h_rt=12:00:00
#$ -l gpu=true

export LANG="en_US.utf8"
export LANGUAGE="en_US:en"

conda activate libkge_new

cd ${HOME}/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 10 && PYTHONPATH=. python ./test2.py  --data pse --model complex --quiet True --mcl True --epochs 100 --batch-size 5000 --regulariser n3 --reg-weight 0.03
