#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -o $HOME/pairh_tuck_covid.out
#$ -e $HOME/pairh_tuck_covid.err
#$ -t 1-1
#$ -l tmem=15G
#$ -l h_rt=96:00:00
#$ -l gpu=true

conda activate libkge_new
export LANG="en_US.utf8"
export LANGUAGE="en_US:en"
cd $HOME/Dissertation/Aladdin/biolink/

test $SGE_TASK_ID -eq 1 && sleep 30 && PYTHONPATH=. python testing/pair_hinge_tucker_covid.py pair_hinge_tucker_covid
